
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "RelevewsService", targetNamespace = "http://ReleveWS/", wsdlLocation = "http://localhost:9191/Relevews?wsdl")
public class RelevewsService
    extends Service
{

    private final static URL RELEVEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RELEVEWSSERVICE_EXCEPTION;
    private final static QName RELEVEWSSERVICE_QNAME = new QName("http://ReleveWS/", "RelevewsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/Relevews?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RELEVEWSSERVICE_WSDL_LOCATION = url;
        RELEVEWSSERVICE_EXCEPTION = e;
    }

    public RelevewsService() {
        super(__getWsdlLocation(), RELEVEWSSERVICE_QNAME);
    }

    public RelevewsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RELEVEWSSERVICE_QNAME, features);
    }

    public RelevewsService(URL wsdlLocation) {
        super(wsdlLocation, RELEVEWSSERVICE_QNAME);
    }

    public RelevewsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RELEVEWSSERVICE_QNAME, features);
    }

    public RelevewsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RelevewsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Relevewss
     */
    @WebEndpoint(name = "relevewssPort")
    public Relevewss getRelevewssPort() {
        return super.getPort(new QName("http://ReleveWS/", "relevewssPort"), Relevewss.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Relevewss
     */
    @WebEndpoint(name = "relevewssPort")
    public Relevewss getRelevewssPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ReleveWS/", "relevewssPort"), Relevewss.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RELEVEWSSERVICE_EXCEPTION!= null) {
            throw RELEVEWSSERVICE_EXCEPTION;
        }
        return RELEVEWSSERVICE_WSDL_LOCATION;
    }

}
